### ISSUE TITLE
Batch Linear Regression

### ISSUE THREAD

**Issue by KUNAL-create-gif** [StephenGrider/MLKits#6]
my error is 
`C:\MLKits-master\regressions\linear-regression.js:37
        const batchQuantity = Math.floor(this.features.shape[0] / this.options.batchSize);
                                                       ^

TypeError: Cannot read property 'shape' of undefined
    at LinearRegression.train (C:\MLKits-master\regressions\linear-regression.js:37:56)
    at Object.<anonymous> (C:\MLKits-master\regressions\index.js:22:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

(https://github.com/KUNAL-create-gif/regressions-)

**Comment by KUNAL-create-gif** [comment]
error is 
C:\MLKits-master\regressions\linear-regression.js:37
        const batchQuantity = Math.floor(this.features.shape[0] / this.options.batchSize);
                                                       ^

TypeError: Cannot read property 'shape' of undefined
    at LinearRegression.train (C:\MLKits-master\regressions\linear-regression.js:37:56)
    at Object.<anonymous> (C:\MLKits-master\regressions\index.js:22:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
